[config.wallpaper]
command = ""
set = false

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = "hyprctl reload"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.hypremoji]
input_path = '~/.config/matugen/templates/hypremoji.css'
output_path = '~/.config/hypremoji/style.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.conky]
input_path = '~/.config/matugen/templates/conky.conf'
output_path = '~/.config/conky/theme.config'
# post_hook = 'pkill -SIGUSR1 conky | conky -c ~/.config/conky/theme.config'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
