$accent = rgba(e7deffff) 
$primary = rgba(e7deffff)
$secondary = rgba(e7dff8ff)
$success = rgba(ffd9e5ff)
$background = rgba(141318ff)
$surface = rgba(141318ff)
$surface-variant = rgba(48454eff)
$on-primary = rgba(33275eff)
$on-secondary = rgba(322e41ff)
$on-surface = rgba(e6e1e9ff)
$on-surface-variant = rgba(cac4cfff)
$outline = rgba(938f99ff)
$outline-variant = rgba(48454eff)