$accent = rgba(e4dfffff) 
$primary = rgba(e4dfffff)
$secondary = rgba(e5dff9ff)
$success = rgba(ffd8e7ff)
$background = rgba(141318ff)
$surface = rgba(141318ff)
$surface-variant = rgba(47464fff)
$on-primary = rgba(2f295fff)
$on-secondary = rgba(312e41ff)
$on-surface = rgba(e5e1e9ff)
$on-surface-variant = rgba(c9c5d0ff)
$outline = rgba(928f99ff)
$outline-variant = rgba(47464fff)