conky.config = {
    background = true,
    update_interval = 1,

    out_to_x = false,
    out_to_wayland = true,

    own_window = true,
    own_window_type = 'override',

    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 80,      
    own_window_colour = "#e7dff8",

    alignment = 'bottom_left',
    gap_x = 20,
    gap_y = 20,                     

    border_inner_margin = 4,
    minimum_width = 140,

    double_buffer = true,

    use_xft = true,
    xftalpha = 1,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    uppercase = true,
};

conky.text = [[
${offset 16}${alignc}${color #e7dff8}${font Rubik:medium:size=60}${time %d}${font}${offset 16}
${voffset 10}${alignc}${color #e7dff8}${font Rubik:medium:size=12}${time %B}${font}
]];
