conky.config = {
    background = true,
    update_interval = 1,

    out_to_x = false,
    out_to_wayland = true,

    own_window = true,
    own_window_type = 'override',

    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,      
    own_window_colour = transparent,

    alignment = 'top_middle',
    gap_x = 20,
    gap_y = 20,                     

    border_inner_margin = 20,       
    minimum_width = 520,

    double_buffer = true,

    use_xft = true,
    xftalpha = 1,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    uppercase = true,
};


conky.text = [[
${alignc}${voffset 40}${color #ccbeff}${font A Black Lives:semiboldbold:size=76}${time %A}${font}
]];
