# --- APPLICATIONS ---
$motrix = $HOME/Applications/Motrix-1.8.19.AppImage
# --- SCRIPTS ---
$launcher = ~/.config/hypr/scripts/rofi.sh launcher
$web_launcher = ~/.config/hypr/scripts/rofi.sh web_launcher
$clipboard = ~/.config/hypr/scripts/rofi.sh clipboard
$screenshot = ~/.config/hypr/scripts/screenshot.sh
$window_only = ~/.config/hypr/scripts/screenshot.sh window
$editor = codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
$wall_selector = ~/.config/hypr/scripts/wall_selector.sh
$wallpaper = ~/.config/hypr/scripts/random_wallpaper.sh

# --- APPLICATION ---
bind = SUPER, D, killactive
bind = SUPER, Return, exec, kitty
bind = SUPER, F, exec, nautilus
bind = SUPER, C, exec, $editor
bind = SUPER + Shift, B, exec, brave
bind = SUPER, B, exec, xdg-open https://youtube.com
bind = SUPER, M, exec, $motrix
bind = SUPER, W, exec, wireshark  # waydroid show-full-ui
bind = SUPER, period, exec, pgrep -x hypremoji && pkill hypremoji ||  hypremoji

# --- ROFI WINDOWS
bind = SUPER, R, exec, $launcher
# bindr = SUPER, Super_L, exec, $web_launcher
bind = SUPER, V, exec, $clipboard
bind = SUPER + Shift, W,  exec, $wall_selector # Wallpaper Selector

#  --- WINDOWS
bind = SUPER, Space, togglefloating     # float current window
bind = SUPER + Shift, F, fullscreen,0     # Force Fullscreen

#  SCREENSHOT
bind = SUPER, P, exec, $screenshot region
bind = , Print, exec, $screenshot full

# SCRIPTS
bind = SUPER, T, exec, $wallpaper -random   # Set Random Wallpaper
bind = SUPER, J, exec, ~/.config/hypr/scripts/waybar.sh toggle      # Toggle Waybar
bind = Alt, Space, exec, ~/.config/hypr/scripts/waybar.sh reload    # Reload Waybar

# --- OTHERS
bind = SUPER, L, exec,  hyprlock --immediate

# WORKSPACES
bind = SUPER, mouse_up, workspace, +1
bind = SUPER, mouse_down, workspace, -1
bind = SUPER, left, workspace, -1
bind = SUPER, right, workspace, +1
bind = Alt, mouse_up, movetoworkspace, +1
bind = Alt, mouse_down, movetoworkspace, -1 
bind = Alt, left, movetoworkspace, -1
bind = Alt, right, movetoworkspace, +1

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

# Move/resize windows with Super + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
